version: "3.4"
services:
  frontend:
    build: ./frontend #dev
    image: michaelguenter/radio-frontend:latest
    container_name: frontend
    ports: 
      - 80:80
    environment:
      - 'CLIENT_API_BASE_URL=http://localhost:8080'
      - 'CLIENT_STREAM_BASE_URL=http://localhost:8081'
  backend_external:
    build: #dev
      context: ./backend
      target: external-web-runtime
    image: michaelguenter/radio-backend-external:latest
    container_name: backend_external
    depends_on:
      - database
    ports:
      - 8080:80
    volumes:
      - backend_external_logs:/var/log/radio
    environment:
      - 'Environment:DbConnectionString=User ID=radio;Password=Abc1234;Host=database;Port=5432;Database=radio;Pooling=true;'
    command: ["./wait-for-it.sh", "database:5432", "--", "dotnet", "Radio.Startup.Web.External.dll"]
  backend_internal:
    build: #dev
      context: ./backend
      target: internal-web-runtime
    image: michaelguenter/radio-backend-internal:latest
    container_name: backend_internal
    depends_on:
      - database
    volumes:
      - backend_internal_logs:/var/log/radio
    environment:
      - 'Environment:DbConnectionString=User ID=radio;Password=Abc1234;Host=database;Port=5432;Database=radio;Pooling=true;'
    command: ["./wait-for-it.sh", "database:5432", "--", "dotnet", "Radio.Startup.Web.Internal.dll"]
  backend_console:
    build: #dev
      context: ./backend
      target: console-runtime
    image: michaelguenter/radio-backend-console:latest
    container_name: backend_console
    depends_on:
      - database
    volumes:
      - backend_console_logs:/var/log/radio
    environment:
      - 'Environment:DbConnectionString=User ID=radio;Password=Abc1234;Host=database;Port=5432;Database=radio;Pooling=true;'
      - 'Environment:MigrationsDbConnectionString=User ID=radio;Password=Abc1234;Host=database;Port=5432;Database=radio;Pooling=true;'
    command: ["./wait-for-it.sh", "database:5432", "--", "dotnet", "Radio.Startup.Console.dll"]
  streaming:
    build: ./streaming #dev
    image: michaelguenter/radio-streaming:latest
    container_name: streaming
    ports:
      - 8081:8000
    volumes:
      - icecast_logs:/var/log/icecast2
    environment:
      - 'ICECAST_LOCATION=Local Internetradio'
      - 'ICECAST_ADMIN_EMAIL=foo@example.com'
      - 'ICECAST_MAX_CLIENTS=100'
      - 'ICECAST_SOURCE_PASSWORD=Abc1234'
      - 'ICECAST_RELAY_PASSWORD=Abc1234'
      - 'ICECAST_ADMIN_USERNAME=admin'
      - 'ICECAST_ADMIN_PASSWORD=Abc1234'
      - 'ICECAST_HOSTNAME=localhost'
      - 'ICECAST_PORT=8000'
      - 'ICECAST_PUBLIC=0'
      - 'ICECAST_STREAM_NAME=Local Stream'
      - 'ICECAST_STREAM_DESCRIPTION=Streaming music.'
  playback:
    build: ./playback #dev
    image: michaelguenter/radio-playback:latest
    container_name: playback
    depends_on:
      - streaming
    volumes:
      - ./data/music:/home/liquidsoap/music
      - liquidsoap_logs:/var/log/liquidsoap
    environment:
      - 'BACKEND_HOST=backend_internal'
      - 'BACKEND_PORT=80'
      - 'ICECAST_HOST=streaming'
      - 'ICECAST_PORT=8000'
      - 'ICECAST_SOURCE_PASSWORD=Abc1234'
  database:
    image: postgres:11.2
    container_name: database
    volumes:
      - database_data:/var/lib/postgresql/data
    environment:
      - 'POSTGRES_USER=radio'
      - 'POSTGRES_PASSWORD=Abc1234'
volumes:
  backend_external_logs:
  backend_internal_logs:
  backend_console_logs:
  icecast_logs:
  liquidsoap_logs:
  database_data: